#ifndef DELAY_AND_SUMC_CUDA_H
#define DELAY_AND_SUMC_CUDA_H

/*extern "C" */

int c_delayAndSum_Algorithm_nearest_SP_CUDA(const float* scanlines,  
                                    const unsigned int* tx,  
                                    const unsigned int* rx,  
                                    const float* lookup_times_tx,  
                                    const float* lookup_times_rx,
                                    const float* amplitudes_tx,  
                                    const float* amplitudes_rx, 
                                    float invdt, 
                                    float t0, 
                                    float fillvalue,
                                    float* result,
                                    int numpoints,
                                    int numsamples,
                                    int numelements, 
                                    int numscanlines,
                                    int NTHREADS,
                                    int txUpdate,
                                    int rxUpdate,
                                    int ExpDataUpdate,
                                    int finaliseOpt);

int c_delayAndSum_Algorithm_nearest_DP_CUDA(const double* scanlines,  
                                    const unsigned int* tx,  
                                    const unsigned int* rx,  
                                    const double* lookup_times_tx,  
                                    const double* lookup_times_rx,
                                    const double* amplitudes_tx,  
                                    const double* amplitudes_rx, 
                                    double invdt, 
                                    double t0, 
                                    double fillvalue,
                                    double* result,
                                    int numpoints,
                                    int numsamples,
                                    int numelements, 
                                    int numscanlines,
                                    int NTHREADS,
                                    int txUpdate,
                                    int rxUpdate,
                                    int ExpDataUpdate,
                                    int finaliseOpt);
                                    
int c_delayAndSum_Algorithm_linear_SP_CUDA(const float* scanlines,  
                                    const unsigned int* tx,  
                                    const unsigned int* rx,  
                                    const float* lookup_times_tx,  
                                    const float* lookup_times_rx,
                                    const float* amplitudes_tx,  
                                    const float* amplitudes_rx, 
                                    float invdt, 
                                    float t0, 
                                    float fillvalue,
                                    float* result,
                                    int numpoints,
                                    int numsamples,
                                    int numelements, 
                                    int numscanlines,
                                    int NTHREADS,
                                    int txUpdate,
                                    int rxUpdate,
                                    int ExpDataUpdate,
                                    int finaliseOpt);

int c_delayAndSum_Algorithm_linear_DP_CUDA(const double* scanlines,  
                                    const unsigned int* tx,  
                                    const unsigned int* rx,  
                                    const double* lookup_times_tx,  
                                    const double* lookup_times_rx,
                                    const double* amplitudes_tx,  
                                    const double* amplitudes_rx, 
                                    double invdt, 
                                    double t0, 
                                    double fillvalue,
                                    double* result,
                                    int numpoints,
                                    int numsamples,
                                    int numelements, 
                                    int numscanlines,
                                    int NTHREADS,
                                    int txUpdate,
                                    int rxUpdate,
                                    int ExpDataUpdate,
                                    int finaliseOpt);                                    

#endif /* DELAY_AND_SUMC_CUDA_H */


